#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use AJT\Toggl\TogglClient;
use Carbon\Carbon;
use Ginq\Ginq;

$apiToken = getenv('TOGGL_API_TOKEN');

$togglClient = TogglClient::factory(array('api_key' => $apiToken));

$workspaces = $togglClient->getWorkspaces(array());

$workspaceId = null;
foreach ($workspaces as $workspace) {
    $workspaceId = $workspace['id'];
}

$projects = $togglClient->getProjects(array(
    'id' => $workspaceId,
));

if (isset($argv[1])) {
    if (!preg_match('/\A[0-9]{4}-[0-9]{2}-[0-9]{2}\z/u', $argv[1])) {
        echo 'The first argument must be specified in YYYY-MM-DD format.', PHP_EOL;
        exit(101);
    }
    $startDate = (new Carbon($argv[1]))->startOfDay();
} else {
    $addedMonths = -1;
    $startDate = Carbon::now()->addMonth($addedMonths)->startOfMonth();
}

if (isset($argv[2])) {
    if (!preg_match('/\A[0-9]{4}-[0-9]{2}-[0-9]{2}\z/u', $argv[2])) {
        echo 'The second argument must be specified in YYYY-MM-DD format.', PHP_EOL;
        exit(101);
    }
    $endDate = (new Carbon($argv[2]))->endOfDay();
} else {
    $endDate = Carbon::now()->endOfMonth();
}

$timeEntries = $togglClient->getTimeEntries([
    'start_date' => $startDate->toIso8601String(),
    'end_date' => $endDate->toIso8601String(),
]);

echo 'project,description,duration,start,tags', PHP_EOL;
Ginq::from($timeEntries)
    ->each(function ($it) use ($projects) {
        $pid = isset($it['pid']) ? $it['pid'] : '';

        $project = Ginq::from($projects)
            ->firstOrElse(array('name' => ''), function (array $project) use ($pid) {
                return $project['id'] === $pid;
            });
        $description = isset($it['description']) ? $it['description'] : '';
        $duration = round(
            (isset($it['duration']) ? ((float) $it['duration']) : 0.0) / (60 * 60),
            2
        );

        $start = '';
        if (isset($it['start'])) {
            $date = new Carbon($it['start']);
            $date->setTimezone(date_default_timezone_get());
            $start = $date->toIso8601String();
        }

        $tags = isset($it['tags']) ? implode($it['tags'], ':') : '';

        echo "{$project['name']},{$description},{$duration},{$start},{$tags}", PHP_EOL;
    })
    ->toArray();
